title: Sustainable Mobility
description: Sustainable Mobility refers to transportation systems and practices that are environmentally friendly,
socially equitable, and economically viable. It aims to meet the mobility needs of people and goods 
while minimizing negative impacts on the environment, reducing energy consumption, and 
promoting social inclusion. Sustainable mobility integrates various modes of transport, such as 
walking, cycling, public transit, and shared mobility, with a focus on reducing reliance on private cars and lowering carbon emissions.
theme: jekyll-theme-cayman
